// Generated by CoffeeScript 1.7.1
var appendPopularMenuResult, getPopularMenus, menuAjaxd;

menuAjaxd = 0;

$(document).ready(function() {
  addInfiniteScroll($('#main_Popular_Menus'), 1000, function() {
    return getPopularMenus(menuAjaxd);
  });
});

getPopularMenus = function(times) {
  $.ajax({
    type: "GET",
    url: 'http://54.178.135.71:8080/CookIEServer/discover_recipelists',
    dataType: 'application/json',
    data: {
      'type': 'popular',
      'times': times
    },
    timeout: 10000,
    success: function(data) {
      var scope;
      data = JSON.parse(data);
      console.log("[SUCCESS]fetch popular menu");
      console.log(data);
      menuAjaxd++;
      $('#main_Popular_Menus').scroller().clearInfinite();
      if (data === null || data.length === 0) {
        $("#main_Popular_Menus").find("#infinite").text("No more menu");
        menuAjaxd--;
        return;
      }
      scope = $("#main_Popular_Menus");
      appendPopularMenuResult(scope, data);
    },
    error: function(data, status) {
      console.log("[ERROR]fetch popular menu: " + status);
      $("#main_Popular_Menus").find("#infinite").text("Error. Try Again?");
      $('#main_Popular_Menus').scroller().clearInfinite();
    }
  });
};

appendPopularMenuResult = function(scope, data) {
  var html, id, idString, list, rating, recipe, results, src, title, _i, _j, _len, _len1, _ref;
  console.log("append menu for scope: " + scope[0].id);
  results = scope.find("#Results");
  results.find(".new").removeClass("new");
  for (_i = 0, _len = data.length; _i < _len; _i++) {
    list = data[_i];
    html = '';
    id = list.list_id;
    title = list.name;
    rating = list.rating;
    if (rating === 0) {
      rating = 'No rating';
    } else {
      rating += " stars";
    }
    html = '<div class="menu_wrapper new" id="Menu' + id + '" menu-id="' + id + '">';
    html += '<h2 class="menu_title">' + title + '&nbsp;&nbsp;&nbsp;<i class="icon star h5">' + rating + '</i>&nbsp;&nbsp;<i class="icon chat h5">comments</i></h2>';
    idString = [];
    html += '<div class="menu_img_wrapper">';
    _ref = list.recipes;
    for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
      recipe = _ref[_j];
      src = recipe.smallURL;
      html += '<img class="menu_img" src="' + src + '">';
      idString.push(recipe.recipe_id);
    }
    html += '</div>';
    html += '<div style="float:left;width:100%;background-color:white;border-radius:5px;"><a id="Cook" class="button red" style="float:right;width:20%;margin-right:5%;" href="#Ingredients</span>">Cook</a><a id="View" class="button green" style="float:right;width:20%;margin-right:2%;" href="#MenuContent">View</a></div><div class="aDivider">&nbsp;</div>';
    html += '</div>';
    results.append(html);
    scope.find("#Menu" + id).attr("data-recipe-ids", JSON.stringify(idString));
    scope.find("#Menu" + id).find("#View")[0].onclick = (function(id) {
      return function() {
        $("#MenuContent").find("#Results").hide();
        $("#MenuContent").find("#Loading").show();
        getMenuContent($("#MenuContent"), id);
      };
    })(id);
    scope.find("#Menu" + id).find("#Cook")[0].onclick = (function(id) {
      return function() {
        $("#Ingredients").find("#Results").hide();
        $("#Ingredients").find("#Loading").show();
        $.ui.loadContent("#Ingredients");
        getCookingIngredientList(scope.find("#Menu" + id).attr("data-recipe-ids"));
      };
    })(id);
  }
  scope.find("#infinite").text("Load More");
};
