// Generated by CoffeeScript 1.7.1
var getKitchenRecipes, kitchenRecipeAjaxd;

kitchenRecipeAjaxd = 0;

$(document).ready(function() {
  addInfiniteScroll($('#main_Kitchen_Recipes'), 3000, function() {
    return getKitchenRecipes(kitchenRecipeAjaxd, self);
  });
});

getKitchenRecipes = function(times) {
  $.ajax({
    type: "GET",
    url: 'http://54.178.135.71:8080/CookIEServer/discover_recipes',
    dataType: 'application/json',
    data: {
      'user_id': window.user_id,
      'token': window.token,
      'type': 'favorite',
      'times': times
    },
    timeout: 10000,
    success: function(data) {
      var scope, scrollerList;
      data = JSON.parse(data);
      console.log("[SUCCESS]fetch kitchen recipes");
      console.log(data);
      kitchenRecipeAjaxd++;
      scrollerList = $('#main_Kitchen_Recipes').scroller();
      scrollerList.clearInfinite();
      if (data.length === 0) {
        $("#main_Kitchen_Recipes").find("#infinite").text("No more recipes");
        kitchenRecipeAjaxd--;
        return;
      }
      scope = $("#main_Kitchen_Recipes");
      appendRecipeResult(scope, data);
    },
    error: function(data, status) {
      console.log("[ERROR]fetch kitchen recipes: " + status);
      console.log(data);
      $("#main_Kitchen_Recipes").find("#infinite").text("Load More");
      $('#main_Kitchen_Recipes').scroller().clearInfinite();
    }
  });
};
