// Generated by CoffeeScript 1.7.1

/* Steps information */
var Step, animationMoveThisStepFromLeftToRight, animationMoveThisStepFromRightToLeft, calculatePercentage, calculateRemainTime, checkFinishPercentageAndChangeTitle, checkNextStep, checkWaitingStepBlocking, checkWaitingStepsFinish, cookingEnded, cookingStarted, extendStepInfo, finishedShowStatus, loadBlockingStep, loadStep, pushStepToWaitingQueue, showTwoUrgentSteps, startTimer, stopTimer, timer, updateNextStepProgressBar, updateWaitingProgressBar;

Step = (function() {

  /* For logging the time used in every step */
  function Step(stepNum, recipeId, stepId, timeDiff) {
    this.stepNum = stepNum;
    this.recipeId = recipeId;
    this.stepId = stepId;
    this.timeDiff = timeDiff;
  }

  return Step;

})();

extendStepInfo = function(step) {

  /* For to be used in related functions */
  step.duration = convertTimeToSeconds(step.time);
  step.finishTime = step.startTime + step.duration;
  step.timeElapsed = 0;
  step.percentage = 0;
  step.remainTime = calculateRemainTime(step);
  return step;
};

calculateRemainTime = function(step) {
  return step.remainTime = step.duration - step.timeElapsed;
};

calculatePercentage = function(step) {
  var remainTime;
  remainTime = calculateRemainTime(step);
  step.percentage = Math.floor(remainTime / step.duration * 100);
  return step.percentage + "%";
};


/* Function definitions */

cookingStarted = function() {

  /* Check if cooking data exist. It should exist when this is called but check anyways. */
  var currentStepNum, finishPercentage;
  if (window.cookingData == null) {
    return;
  }
  currentStepNum = window.currentStepNum;
  window.currentTime = 0;
  window.waitingStepQueue = [];
  window.stepsTimeUsed = [];
  window.cookingStartTime = new Date();
  console.log("cooking started");
  $(".waiting_step_outer_wrapper").addClass('invisible');
  finishPercentage = Math.ceil((currentStepNum + 1) / window.cookingData.steps.length * 100);
  $("#Step").attr("data-title", "Step " + (currentStepNum + 1) + " (" + finishPercentage + "%)");
  loadStep(currentStepNum);
  setTimeout(function() {
    return timer();
  }, 1000);
};

cookingEnded = function() {
  return stopTimer();
};


/* Timer: for clocking the cook process */

timer = function() {
  window.currentStep.timeElapsed += 1;
  window.waitingStepQueue.forEach(function(step) {
    step.timeElapsed += 1;
    return calculateRemainTime(step);
  });

  /* Check waiting queue status */
  checkWaitingStepsFinish();

  /* Update progress bars */
  updateNextStepProgressBar();
  showTwoUrgentSteps();
  startTimer();
};

startTimer = function() {
  clearTimeout(window.lastId);
  window.lastId = setTimeout(function() {
    return timer();
  }, 1000);
};

stopTimer = function() {
  return clearTimeout(window.lastId);
};


/* Steps */

loadStep = function(stepNum) {
  var nextBtn, nextStep, scope, thisStep;
  console.log("load step#" + stepNum);
  thisStep = window.cookingData.steps[stepNum];
  window.currentTime = thisStep.startTime;
  window.currentStep = extendStepInfo(thisStep);
  window.currentStepNum = stepNum;
  animationMoveThisStepFromLeftToRight();
  checkFinishPercentageAndChangeTitle();
  scope = $("#Step");
  scope.find(".this_step_recipe_name").html(thisStep.recipeName);
  scope.find(".this_step_digest").html(thisStep.digest);
  nextStep = window.cookingData.steps[stepNum + 1];
  if (nextStep != null) {
    scope.find(".next_step_name").html(trimStringLength(nextStep.stepName));
    scope.find(".next_step_time").html("" + thisStep.timeElapsed + "/" + thisStep.time);
    scope.find(".step_next_btn").html("下一步");
  } else {
    scope.find(".next_step_name").html("最後一步");
    scope.find(".next_step_time").html("");
    scope.find(".step_next_btn").html("完成");
  }
  nextBtn = scope.find(".step_next_btn");
  nextBtn.unbind('click');
  nextBtn.click(function() {
    checkNextStep();
  });
};

loadBlockingStep = function(index) {
  var nextBtn, scope, step;
  console.log("load blocking step, index:" + index);
  console.log(window.waitingStepQueue);
  step = window.waitingStepQueue.splice(index, 1)[0];
  showTwoUrgentSteps();
  window.currentStep = step;
  animationMoveThisStepFromRightToLeft();
  scope = $("#Step");
  scope.find(".this_step_recipe_name").html(step.recipeName);
  scope.find(".this_step_digest").html("" + step.digest);
  nextBtn = scope.find(".step_next_btn");
  nextBtn.html("等待完成");
  nextBtn.unbind('click');
  nextBtn.click(function() {
    checkNextStep(true);
  });
};

checkNextStep = function(blocked) {
  var nextStep, stepNum, thisStep, thisStepFinishTime, timeDiff;
  if (blocked == null) {
    blocked = 0;
  }
  thisStep = window.currentStep;
  thisStepFinishTime = thisStep.finishTime;
  if ((nextStep = window.cookingData.steps[window.currentStepNum + 1]) == null) {

    /* There is no next step */
    console.log("finished");
    $.ui.loadContent("Finish");
    return;
  }

  /* Check if there is a step blocking in the waiting queue */
  if (checkWaitingStepBlocking(thisStep, nextStep)) {
    return;
  }

  /* No blocking step -> load next step */
  timeDiff = nextStep.startTime - (thisStep.startTime + thisStep.timeElapsed);
  if (thisStep.people || blocked) {
    stepNum = !blocked ? window.currentStepNum : window.cookingData.steps.lastIndexOf(thisStep);
    window.stepsTimeUsed.push(new Step(stepNum, thisStep.recipeId, thisStep.stepId, timeDiff));
  } else {
    pushStepToWaitingQueue(thisStep);
  }
  loadStep(window.currentStepNum + 1);
};

pushStepToWaitingQueue = function(step, currentTime) {
  console.log("push " + window.currentStepNum + ": " + step.digest + " into queue");
  window.waitingStepQueue.push(step);
  window.waitingStepQueue.sort(function(a, b) {
    return b.remainTime - a.remainTime;
  });
  console.log(window.waitingStepQueue);
  showTwoUrgentSteps();
};


/* Checks */

checkWaitingStepBlocking = function(thisStep, nextStep) {
  var flag, waitingQueue;
  flag = false;
  waitingQueue = window.waitingStepQueue;
  if (thisStep.finishTime < nextStep.startTime) {

    /* This step does not directly lead to next step -> there is a blocking step in waiting queue */
    waitingQueue.forEach(function(waitingStep) {
      var waitingStepIndex;
      if (waitingStep.finishTime === nextStep.startTime) {

        /* The blocking step is found */
        waitingStepIndex = waitingQueue.lastIndexOf(waitingStep);
        loadBlockingStep(waitingStepIndex);
        flag = true;
      }
    });
  }
  if (flag === true) {
    return;
  }

  /* Check the waiting steps for next step's previous steps */
  waitingQueue.forEach(function(waitingStep) {
    var waitingStepIndex;
    if (waitingStep.recipeId === nextStep.recipeId) {

      /* There is a step with the same recipeId as next step in the waiting queue. */
      waitingStepIndex = waitingQueue.lastIndexOf(waitingStep);
      loadBlockingStep(waitingStepIndex);
      flag = true;
    }
  });
  return flag;
};

checkWaitingStepsFinish = function() {
  var queue, queueLen;
  queue = window.waitingStepQueue;
  queueLen = queue.length;
  queue.forEach(function(waitingStep) {
    var index, step;
    if (waitingStep.remainTime <= 0) {

      /* Finished */
      index = queue.lastIndexOf(waitingStep);
      step = queue.splice(index, 1)[0];
      showTwoUrgentSteps();
      alert("Step finished: " + step.digest);
    }
  });
};

checkFinishPercentageAndChangeTitle = function() {
  var finishPercentage, stepNum;
  stepNum = window.currentStepNum;
  finishPercentage = Math.ceil((stepNum + 1) / window.cookingData.steps.length * 100);
  $.ui.setTitle("Step " + (stepNum + 1) + " (" + finishPercentage + "%)");
};


/* Update functions */

showTwoUrgentSteps = function() {
  var nextNextStep, nextStep, queueLen, waitingQueue;
  waitingQueue = window.waitingStepQueue;
  queueLen = waitingQueue.length;
  nextStep = waitingQueue[queueLen - 1];
  nextNextStep = waitingQueue[queueLen - 2];
  if (queueLen === 1) {
    updateWaitingProgressBar($("#NextNextWaitingStep"), nextStep);
    updateWaitingProgressBar($("#NextWaitingStep"), nextNextStep);
  } else {
    updateWaitingProgressBar($("#NextNextWaitingStep"), nextNextStep);
    updateWaitingProgressBar($("#NextWaitingStep"), nextStep);
  }

  /*
  	if nextStep? and nextNextStep?
  		console.log "enough steps. steps:#{nextStep.stepNum}, #{nextNextStep.stepNum}"
  	else if nextStep?
  		console.log "not enough steps. step:#{nextStep.stepNum}"
  	else
  		console.log "no step waiting"
   */
};

updateNextStepProgressBar = function() {
  var nextStep, thisStep, timeElapsed;
  thisStep = window.currentStep;
  timeElapsed = parseSecondsToTime(thisStep.timeElapsed);
  nextStep = $("#NextStep");
  nextStep.find("#ProgressRemainTime").html("" + timeElapsed + "/" + thisStep.time);
};

updateWaitingProgressBar = function(scope, step) {
  var progressBar, progressName, progressRemainTime;
  progressBar = scope.find("#ProgressBar");
  progressName = scope.find("#ProgressName");
  progressRemainTime = scope.find("#ProgressRemainTime");
  if (step == null) {

    /* step = null: hide empty progress bar */
    $(scope[0].parentNode).addClass('invisible');
  } else {
    progressBar.css3Animate({
      width: "" + (calculatePercentage(step)) + "%",
      time: '500ms'
    });
    progressName.html(trimStringLength(step.stepName));
    progressRemainTime.html(parseSecondsToTime(step.remainTime));
    $(scope[0].parentNode).removeClass('invisible');
  }
};

finishedShowStatus = function() {
  var scope, timeElapsed;
  timeElapsed = (new Date()) - window.cookingStartTime;
  timeElapsed = parseSecondsToTime(Math.floor(timeElapsed / 1000));
  scope = $("#Finish");
  scope.find("#TotalTimeSpent").html(timeElapsed);
  scope.find("#OriginalTime").html(window.cookingData.originTime);
};


/* Animation functions */

animationMoveThisStepFromLeftToRight = function() {
  var thisStep;
  thisStep = window.currentStep;
  $('.this_step_inner_wrapper').addClass('animate_old');
  $('.this_step_outer_wrapper').append($('<div class="this_step_inner_wrapper animate_new">'));
  $('.this_step_inner_wrapper.animate_new').append($('<div class="this_step_recipe_name">').html(thisStep.recipeName));
  $('.this_step_inner_wrapper.animate_new').append($('<h3 class="this_step_digest">').html(thisStep.digest));
  $('.this_step_inner_wrapper.animate_old').css3Animate({
    x: 500,
    time: 300,
    success: function() {
      $('.this_step_inner_wrapper.animate_old').remove();
    }
  });
  $('.this_step_inner_wrapper.animate_new').css3Animate({
    x: -500,
    time: 10,
    success: function() {
      $('.this_step_inner_wrapper.animate_new').css3Animate({
        x: 500,
        time: 300,
        previous: true,
        success: function() {
          $('.animate_new').removeClass('animate_new');
        }
      });
    }
  });
};

animationMoveThisStepFromRightToLeft = function() {
  var thisStep;
  thisStep = window.currentStep;
  $('.this_step_inner_wrapper').addClass('animate_old');
  $('.this_step_outer_wrapper').append($('<div class="this_step_inner_wrapper animate_new">'));
  $('.this_step_inner_wrapper.animate_new').append($('<div class="this_step_recipe_name">').html(thisStep.recipeName));
  $('.this_step_inner_wrapper.animate_new').append($('<h3 class="this_step_digest">').html(thisStep.digest));
  $('.this_step_inner_wrapper.animate_old').css3Animate({
    x: -500,
    time: 300,
    success: function() {
      $('.this_step_inner_wrapper.animate_old').remove();
    }
  });
  $('.this_step_inner_wrapper.animate_new').css3Animate({
    x: 500,
    time: 10,
    success: function() {
      $('.this_step_inner_wrapper.animate_new').css3Animate({
        x: -500,
        time: 300,
        previous: true,
        success: function() {
          $('.animate_new').removeClass('animate_new');
        }
      });
    }
  });
};
