// Generated by CoffeeScript 1.7.1
window.lastId = -1;

window.deckChanged = true;


/* Cooking */

window.cookingData = null;

window.currentStepNum = 0;

window.currentStep = null;

window.currentTime = 0;

window.waitingStepQueue = [];

window.stepsTimeUsed = [];

window.cookingStartTime = null;


/* Deck */

window.recipesInDeck = [];

window.recipesExist = -1;
