// Generated by CoffeeScript 1.7.1
window.lastId = -1;

window.mode = 0;


/* Cooking */

window.cookingData = null;

window.currentStep = null;


/* User */


/*
window.user_id = 4
window.token = "d3c4e8360c80aecf0d4224f49ad051c0"
 */
