// Generated by CoffeeScript 1.7.1
var checkIfLogin, login, updateUserPanel;

login = function() {

  /* Initiate a pop-up prompt */
  return $.ui.popup({
    title: 'Log in',
    message: '<form><label>Username</label><input id="login-username" type="text" placeholder="username"><label>Password</label><input id="login-password" type="password" placeholder="password">',
    cancelText: 'Cancel',
    cancelCallback: function() {
      return console.log("login cancelled");
    },
    doneText: 'Login',
    doneCallback: function() {
      var data, password, username;
      console.log("login");
      username = $('#login-username').val();
      password = $('#login-password').val();
      password = calcMD5(password);
      $.ui.showMask("Logging in...");

      /* Send the data to server to log in */
      data = {
        user_name: username,
        password: password
      };
      data = JSON.stringify(data);
      $.ajax({
        type: 'POST',
        url: 'http://54.178.135.71:8080/CookIEServer/temp_login',
        contentType: 'application/json',
        data: data,
        timeout: 10000,
        success: function(data) {

          /* Login success */
          data = JSON.parse(data);
          console.log("[SUCCESS] logging in");
          console.log(data);

          /* Insert value to DB */
          AddValueToDB(data.token, data.userId);

          /* Store it in global variable */
          window.token = data.token;
          window.user_id = data.userId;

          /* Update user panel after logged in */
          updateUserPanel();
          console.log("" + data.token + ", " + data.userId);
          $.ui.hideMask();
          alert("Login Success.");
        },
        error: function(resp) {

          /* Login failed */
          console.log("[ERROR] logging in");
          console.log(resp);
          $.ui.hideMask();
          if (resp.status === 404) {
            alert("Login failed: " + (JSON.parse(resp.response).error));
          }
        }
      });
    }
  });
};


/* Check if login whenever switched to Kitchen (called in loadedPanel) */

checkIfLogin = function() {
  if (!window.openDatabase) {
    alert('Database are not supported in this browser.');
    return;
  }
  if ((window.token != null) && (window.user_id != null)) {

    /* User already logged in */
    console.log("Already logged in.");
    return;
  }

  /* No login data. Try retrieve it from DB. */
  db.transaction(function(transaction) {

    /* UserId is actually the indexing ID. */
    var sql;
    sql = 'SELECT * FROM `CookieUsers` WHERE `UserId` = (SELECT max(`UserId`) FROM `CookieUsers`)';
    transaction.executeSql(sql, [], function(transaction, result) {

      /* success handler */
      var user;
      if (result != null) {
        user = result.rows.item(0);
        console.log(user);
        console.log("User found. user_id: " + user.ID + ", token: " + user.Token);

        /* Data exists in DB. Logged in. */
        console.log("Logged in after checking DB");
        window.token = user.Token;
        window.user_id = user.ID;

        /* Update user panel after logged in */
        updateUserPanel();
      }
    }, errorHandler, function(transaction, result) {

      /* null handler */

      /* No user data in DB. Redirect to sign up page. */
      console.log("Not logged in");
      alert("Please log in or sign up to use the Kitchen.");
      $.ui.loadContent("#User");
    });
  });
};

updateUserPanel = function() {

  /* TODO retrieve more data like Username and Cooking Time from Server? */
  console.log("Update user panel");
};
