// Generated by CoffeeScript 1.7.1
var addThisRecipeToKitchen, convertTimeToSeconds, deleteSelectedRecipes, findChosenRecipeId, loadPopularRecipes, parseSecondsToTime, parseTimeToMinutes, recipeAjaxd, resetSelectedRecipe;

$(document).ready(function() {
  loadPopularRecipes();
  loadPopularMenus();
});

deleteSelectedRecipes = function() {
  var ans, data, selectedId;
  selectedId = findChosenRecipeId();
  if (selectedId.length === 0) {
    return;
  }
  console.log("deleting recipes " + selectedId);
  ans = confirm("Deleteing recipes from Kitchen. Are you sure?");
  if (ans === false) {
    return;
  }
  data = {
    'type': 'recipe',
    'recipes': selectedId,
    'user_id': window.user_id,
    'token': window.token
  };
  data = JSON.stringify(data);
  console.log(data);
  return $.ajax({
    type: 'DELETE',
    url: 'http://54.178.135.71:8080/CookIEServer/favorite',
    dataType: 'application/json',
    data: data,
    timeout: 10000,
    success: function(data) {
      console.log("[SUCCESS] deleting recipes #" + selectedId);
      console.log(data);
      reloadKitchenRecipes();
    },
    error: function(data, status) {
      console.log("[ERROR] deleting recipes #" + selectedId);
      console.log(data);
    }
  });
};

recipeAjaxd = 0;

loadPopularRecipes = function() {
  var scope;
  scope = $('#main_Popular_Recipes');
  scope.find('#Results').html("");
  scope.find("#infinite").text("Reloading...");
  recipeAjaxd = 0;
  getPopularRecipes(recipeAjaxd);
};

findChosenRecipeId = function() {
  var recipeSelectedId;
  recipeSelectedId = [];
  $('#main_Kitchen_Recipes').find('.chosen').forEach(function(elem) {
    return recipeSelectedId.push(elem.getAttribute('data-recipe-id'));
  });
  console.log(recipeSelectedId);
  return recipeSelectedId;
};

addThisRecipeToKitchen = function() {
  var data, recipeId;
  recipeId = $('#RecipeContent').find('#RecipeImg').attr('data-recipe-id');
  console.log("add " + recipeId + " to kitchen");
  data = {
    user_id: window.user_id,
    token: window.token,
    type: 'recipe',
    recipe_id: recipeId
  };
  data = JSON.stringify(data);
  $.ajax({
    type: 'POST',
    url: 'http://54.178.135.71:8080/CookIEServer/favorite',
    contentType: 'application/json',
    data: data,
    timeout: 10000,
    success: function(data) {
      console.log("[SUCCESS] add " + recipeId + " to kitchen");
      console.log(data);
      alert("Done!");
      reloadKitchenRecipes();
    },
    error: function(resp) {
      console.log("[ERROR] add " + recipeId + " to kitchen");
      console.log(resp);
      if (resp.status === 404) {
        alert("Oops! The recipe is already in Kitchen!");
      }
    }
  });
};

resetSelectedRecipe = function() {
  $('#main_Kitchen_Recipes').find('.chosen').removeClass('chosen');
};

parseTimeToMinutes = function(time) {
  time = time.split(":");
  return time = parseInt(time[0]) * 60 + parseInt(time[1]) + parseInt(time[2]) / 60;
};

convertTimeToSeconds = function(time) {
  time = time.split(":");
  return time = parseInt(time[0]) * 3600 + parseInt(time[1]) * 60 + parseInt(time[2]);
};

parseSecondsToTime = function(seconds) {
  var hour, min;
  hour = Math.floor(seconds / 3600);
  seconds %= 3600;
  hour = hour < 10 ? "0" + hour : hour;
  min = Math.floor(seconds / 60);
  seconds %= 60;
  min = min < 10 ? "0" + min : min;
  seconds = seconds < 10 ? "0" + seconds : seconds;
  return "" + hour + ":" + min + ":" + seconds;
};
